# Dependencies

In [218]:
import torch
import numpy as np

# array_like
   - list
      - Used for storing elements of different data types
      - Flexible: there is no length & shape limit
      - Not optimized for mathematical operations
   - numpy.ndarray
      - Implemented in C
      - Used for mathematical operations
      - Arrays are homogeneous: they can store elements of the same data type
   - troch.Tensor
      - PyTorch's core functionality is implemented in C++
      - Optimized for deep learning operations e.g. auto gradient
      - Support GPU acceleration [NVIDIA GPUs]

In [219]:
# scalar : 0-dimensional array/tensor
scalar_1 = 2
scalar_2 = np.array(2)
scalar_3 = torch.tensor(2)

# log
print(f"scalar_1: {scalar_1} | ndim: 0 | dtype: {type(scalar_1)}")
print(f"scalar_2: {scalar_2} | ndim: {scalar_2.ndim} | dtype: {scalar_2.dtype}")
print(f"scalar_3: {scalar_3} | ndim: {scalar_3.ndim} | dtype: {scalar_3.dtype}")

scalar_1: 2 | ndim: 0 | dtype: <class 'int'>
scalar_2: 2 | ndim: 0 | dtype: int32
scalar_3: 2 | ndim: 0 | dtype: torch.int64


In [220]:
# vector : 1-dimensional list/array/tensor
vector_1 = [1, 2, 3]
vector_2 = np.array(vector_1)
vector_3 = torch.tensor(vector_1)

# log
print(f"vector_1: {str(vector_1):<17} | ndim: 1 | dtype: {type(vector_1[0])}")
print(f"vector_2: {str(vector_2):<17} | ndim: {vector_2.ndim} | dtype: {vector_2.dtype}")
print(f"vector_3: {vector_3} | ndim: {vector_3.ndim} | dtype: {vector_3.dtype}")

vector_1: [1, 2, 3]         | ndim: 1 | dtype: <class 'int'>
vector_2: [1 2 3]           | ndim: 1 | dtype: int32
vector_3: tensor([1, 2, 3]) | ndim: 1 | dtype: torch.int64


In [221]:
# matrix : 2-dimensional list/array/tensor
matrix_1 = [[0, 1], [2, 3]]
matrix_2 = np.array(matrix_1)
matrix_3 = torch.tensor(matrix_1)

# log
print(f"matrix_1:\n{str(matrix_1):<11}\nndim: 2\ndtype: {type(matrix_1[0][0])}")
print('-' * 50)
print(f"matrix_2:\n{str(matrix_2):<11}\nndim: {matrix_2.ndim}\ndtype: {matrix_2.dtype}")
print('-' * 50)
print(f"matrix_3:\n{matrix_3}\nndim: {matrix_3.ndim}\ndtype: {matrix_3.dtype}")

matrix_1:
[[0, 1], [2, 3]]
ndim: 2
dtype: <class 'int'>
--------------------------------------------------
matrix_2:
[[0 1]
 [2 3]]
ndim: 2
dtype: int32
--------------------------------------------------
matrix_3:
tensor([[0, 1],
        [2, 3]])
ndim: 2
dtype: torch.int64


# Tensors

In [222]:
# 0-dimensional
t1 = torch.tensor(12)
t2 = torch.ones(size= ())

# 1-dimensional
t3 = torch.empty(size= (1,))

# 2-dimensional
t4 = torch.rand(size= (2, 3))

# 3-dimensional
t5 = torch.zeros(size= (2, 2, 3))

# log
for i in range(5):
    print(f"t{i+1}:\n{eval(f't{i+1}')}")
    print(f"t{i+1}.size(): {eval(f't{i+1}').size()}")
    print(f"t{i+1}.ndim  : {eval(f't{i+1}').ndim}")
    print(f"t{i+1}.dtype : {eval(f't{i+1}').dtype}")
    print(f"type(t{i+1}) : {type(eval(f't{i+1}'))}")
    print('-' * 50)

t1:
12
t1.size(): torch.Size([])
t1.ndim  : 0
t1.dtype : torch.int64
type(t1) : <class 'torch.Tensor'>
--------------------------------------------------
t2:
1.0
t2.size(): torch.Size([])
t2.ndim  : 0
t2.dtype : torch.float32
type(t2) : <class 'torch.Tensor'>
--------------------------------------------------
t3:
tensor([6.0884e+31])
t3.size(): torch.Size([1])
t3.ndim  : 1
t3.dtype : torch.float32
type(t3) : <class 'torch.Tensor'>
--------------------------------------------------
t4:
tensor([[0.8219, 0.7519, 0.9828],
        [0.5720, 0.7597, 0.3900]])
t4.size(): torch.Size([2, 3])
t4.ndim  : 2
t4.dtype : torch.float32
type(t4) : <class 'torch.Tensor'>
--------------------------------------------------
t5:
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
t5.size(): torch.Size([2, 2, 3])
t5.ndim  : 3
t5.dtype : torch.float32
type(t5) : <class 'torch.Tensor'>
--------------------------------------------------


## element-wise operations

In [223]:
t1 = torch.rand(size= (2, 2))
t2 = torch.ones(size= (2, 2), dtype= torch.int64)

c1 = t1 + t2  # torch.add(t1, t2)      | t1.add(t2)
c2 = t1 * t2  # torch.multiply(t1, t2) | t1.multiply(t2)
c3 = t1 ** t2 # torch.pow(t1, t2)      | t1.pow(t2)

# log
for i in range(2):
    print(f"t{i+1}:\n{eval(f't{i+1}')}\n")
print('-' * 50)
for i in range(3):
    print(f"c{i+1}:\n{eval(f'c{i+1}')}\n")

t1:
tensor([[0.6694, 0.4539],
        [0.2407, 0.3143]])

t2:
tensor([[1, 1],
        [1, 1]])

--------------------------------------------------
c1:
tensor([[1.6694, 1.4539],
        [1.2407, 1.3143]])

c2:
tensor([[0.6694, 0.4539],
        [0.2407, 0.3143]])

c3:
tensor([[0.6694, 0.4539],
        [0.2407, 0.3143]])



## broadcasting

In [224]:
t1 = torch.rand(2, 2)

c1 = t1 + 1
c2 = t1 * 10
c3 = t1 ** 2

# log
print(f"t1:\n{t1}\n")
print('-' * 50)
for i in range(3):
    print(f"c{i+1}:\n{eval(f'c{i+1}')}\n")

t1:
tensor([[0.7521, 0.3261],
        [0.5800, 0.2857]])

--------------------------------------------------
c1:
tensor([[1.7521, 1.3261],
        [1.5800, 1.2857]])

c2:
tensor([[7.5209, 3.2610],
        [5.8002, 2.8573]])

c3:
tensor([[0.5656, 0.1063],
        [0.3364, 0.0816]])



## index & slice

In [225]:
t1 = torch.rand(3, 4)

i1 = t1[0]
i2 = t1[1, 2]
s1 = t1[:, 1]
s2 = t1[0, :]

# log
print(f"t1:\n{t1}")
print('-' * 50)
for i in range(2):
    print(f"i{i+1}: {eval(f'i{i+1}')}")
for i in range(2):
    print(f"s{i+1}: {eval(f's{i+1}')}")

t1:
tensor([[0.6583, 0.2651, 0.4245, 0.1784],
        [0.3136, 0.6300, 0.5987, 0.9762],
        [0.0973, 0.7832, 0.0826, 0.9032]])
--------------------------------------------------
i1: tensor([0.6583, 0.2651, 0.4245, 0.1784])
i2: 0.5986832976341248
s1: tensor([0.2651, 0.6300, 0.7832])
s2: tensor([0.6583, 0.2651, 0.4245, 0.1784])


## item
   - Returns the value of this tensor as a standard Python number. This only works for tensors with one element

In [226]:
t1 = torch.rand(3, 4)
i1 = t1[0, 0]
i2 = t1[0, 0].item()

# log
print(f"t1:\n{t1}")
print('-' * 50)
print(f"i1: {i1}")
print(f"i1.dtype: {i1.dtype}\n")
print(f"i2: {i2}")
print(f"type(i2): {type(i2)}\n")

t1:
tensor([[0.2070, 0.5092, 0.6879, 0.3051],
        [0.4795, 0.4779, 0.0013, 0.1518],
        [0.0909, 0.4201, 0.1391, 0.1313]])
--------------------------------------------------
i1: 0.20696145296096802
i1.dtype: torch.float32

i2: 0.20696145296096802
type(i2): <class 'float'>



## reshape & view
   - view: a new tensor with the same data as the `self` tensor but of a different `shape`.
   - reshape: This method returns a `view` if shape is compatible with the current `shape`.

In [227]:
t1 = torch.rand(4, 4)

reshape_1 = t1.reshape(2, 8)
reshape_2 = t1.reshape(2, -1, 2)

# log
print(f"t1:\n{t1}", end= '\n\n')
print('-' * 50)
for i in range(2):
    print(f"reshape_{i+1}:\n{eval(f'reshape_{i+1}')}")
    print()

t1:
tensor([[0.6364, 0.1796, 0.3888, 0.9673],
        [0.3721, 0.6368, 0.9027, 0.3573],
        [0.7786, 0.9309, 0.7517, 0.5448],
        [0.8744, 0.8927, 0.3436, 0.9103]])

--------------------------------------------------
reshape_1:
tensor([[0.6364, 0.1796, 0.3888, 0.9673, 0.3721, 0.6368, 0.9027, 0.3573],
        [0.7786, 0.9309, 0.7517, 0.5448, 0.8744, 0.8927, 0.3436, 0.9103]])

reshape_2:
tensor([[[0.6364, 0.1796],
         [0.3888, 0.9673],
         [0.3721, 0.6368],
         [0.9027, 0.3573]],

        [[0.7786, 0.9309],
         [0.7517, 0.5448],
         [0.8744, 0.8927],
         [0.3436, 0.9103]]])



## copy a tensor
   - clone : This function is differentiable, so gradients will flow back from the result of this operation to `input`
   - detach: Returns a new Tensor, detached from the current graph

In [228]:
t1 = torch.zeros(size= (2, 3), requires_grad= True)
t2 = t1.detach()
t3 = t1.clone()

# log
for i in range(2):
    print(f"t{i+2}:\n{eval(f't{i+2}')}")

t2:
tensor([[0., 0., 0.],
        [0., 0., 0.]])
t3:
tensor([[0., 0., 0.],
        [0., 0., 0.]], grad_fn=<CloneBackward0>)


## torch.Tensor to numpy.ndarray

In [229]:
t1 = torch.ones(2, 3)

n1 = t1.numpy()   # share the same memory location
n2 = np.array(t1) # copy

n1[0, 0] = 0
n2[0, 1] = 0

# log
print(f"t1:\n{t1}")
print(f"type(t1): {type(t1)}")
print('-' * 50)
for i in range(2):
    print(f"n{i+1}:\n{eval(f'n{i+1}')}")
    print(f"type(n{i+1}): {eval(f'type(n{i+1})')}\n")

t1:
tensor([[0., 1., 1.],
        [1., 1., 1.]])
type(t1): <class 'torch.Tensor'>
--------------------------------------------------
n1:
[[0. 1. 1.]
 [1. 1. 1.]]
type(n1): <class 'numpy.ndarray'>

n2:
[[1. 0. 1.]
 [1. 1. 1.]]
type(n2): <class 'numpy.ndarray'>



## numpy.ndarray to torch.Tensor

In [230]:
n1 = np.ones(shape= (2, 3))

t1 = torch.from_numpy(n1) # share the same memory location
t2 = torch.tensor(n1)     # copy

t1[0, 0] = 0
t2[0, 1] = 0

# log
print(f"n1:\n{n1}")
print(f"type(n1): {type(n1)}")
print('-' * 50)
for i in range(2):
    print(f"t{i+1}:\n{eval(f't{i+1}')}")
    print(f"type(t{i+1}): {eval(f'type(t{i+1})')}\n")

n1:
[[0. 1. 1.]
 [1. 1. 1.]]
type(n1): <class 'numpy.ndarray'>
--------------------------------------------------
t1:
tensor([[0., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
type(t1): <class 'torch.Tensor'>

t2:
tensor([[1., 0., 1.],
        [1., 1., 1.]], dtype=torch.float64)
type(t2): <class 'torch.Tensor'>



## tensor on GPU
   - tensor on GPU can not be converted to np.ndarray directly

In [231]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
# or
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')

# log
print(device)

cuda


In [232]:
t1 = torch.ones(2, 3)
t2 = t1.to(device)

t1[0, 0] = 0

# log
print(f"t1.device: {t1.device}")
print(f"t2.device: {t2.device}")
print(f"t2:\n{t2}")

t1.device: cpu
t2.device: cuda:0
t2:
tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')


In [233]:
t1 = torch.ones(2, 3, device= device)

try:
    n1 = t1.numpy()
except TypeError as e:
    print(e)

can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.


In [234]:
t1 = torch.ones(2, 3, device= device)

n2 = t1.cpu().numpy()

# log
print(f"n2:\n{n2}")

n2:
[[1. 1. 1.]
 [1. 1. 1.]]


In [235]:
t1 = torch.ones(2, 3, device= device)
t2 = torch.ones(2, 3).to(device)
t3 = torch.ones(2, 3).cuda()

# log
print(t1.device)
print(t2.device)
print(t3.device)

cuda:0
cuda:0
cuda:0


## Notes

### what you see is not necessarily the actual value

In [236]:
t1 = torch.rand(size= (2, 3))

# log
print(t1[0, 0])
print(t1[0, 0].item())

tensor(0.5098)
0.509786069393158


### torch.float32 is preferred rather than torch.float64
   1. Memory Efficiency
   2. Speed
   3. Compatibility: Some deep learning libraries and models are optimized for `torch.float32` operations. Using `torch.float64` may lead to compatibility issues or slower performance in certain cases.

Note:
   - `torch.float32` often referred to as `float`
   - `torch.float64` often referred to as `double`