📝 **Author:** Amirhossein Heydari - 📧 **Email:** amirhosseinheydari78@gmail.com - 📍 **Linktree:** [linktr.ee/mr_pylin](https://linktr.ee/mr_pylin)

---

# Dependencies

In [30]:
import numpy as np
import torch

# array_like Sequences
   - `list`
      - Used for storing elements of different data types
      - Flexible: there is no length & shape limit
      - Not optimized for mathematical operations
   - `numpy.ndarray`
      - Implemented in C
      - Used for mathematical operations
      - Arrays are homogeneous: they can store elements of the same data type
   - `troch.Tensor`
      - PyTorch's core functionality is implemented in C++
      - Optimized for deep learning operations e.g. auto gradient
      - Support GPU acceleration [NVIDIA/AMD GPUs]

📝 **Docs**:
   - More on Lists: [docs.python.org/3/tutorial/datastructures.html#more-on-lists](https://docs.python.org/3/tutorial/datastructures.html#more-on-lists)
   - `numpy.ndarray`: [numpy.org/doc/stable/reference/generated/numpy.ndarray.html](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)
   - `torch.Tensor`: [pytorch.org/docs/stable/tensors.html](https://pytorch.org/docs/stable/tensors.html)

📚 **Tutorials**:
   - Tensors: [pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html)

In [31]:
# scalar : 0-dimensional array/tensor
scalar_1 = 2
scalar_2 = np.array(2)
scalar_3 = torch.tensor(2)

# log
print(f"scalar_1: {scalar_1} | ndim: 0 | dtype: {type(scalar_1)}")
print(f"scalar_2: {scalar_2} | ndim: {scalar_2.ndim} | dtype: numpy.{scalar_2.dtype}")
print(f"scalar_3: {scalar_3} | ndim: {scalar_3.ndim} | dtype: {scalar_3.dtype}")

scalar_1: 2 | ndim: 0 | dtype: <class 'int'>
scalar_2: 2 | ndim: 0 | dtype: numpy.int32
scalar_3: 2 | ndim: 0 | dtype: torch.int64


In [32]:
# vector : 1-dimensional list/array/tensor
vector_1 = [1, 2, 3]
vector_2 = np.array(vector_1)
vector_3 = torch.tensor(vector_1)

# log
print(f"vector_1: {str(vector_1):<17} | ndim: 1 | dtype: {type(vector_1[0])}")
print(f"vector_2: {str(vector_2):<17} | ndim: {vector_2.ndim} | dtype: numpy.{vector_2.dtype}")
print(f"vector_3: {vector_3} | ndim: {vector_3.ndim} | dtype: {vector_3.dtype}")

vector_1: [1, 2, 3]         | ndim: 1 | dtype: <class 'int'>
vector_2: [1 2 3]           | ndim: 1 | dtype: numpy.int32
vector_3: tensor([1, 2, 3]) | ndim: 1 | dtype: torch.int64


In [33]:
# matrix : 2-dimensional list/array/tensor
matrix_1 = [[0, 1], [2, 3]]
matrix_2 = np.array(matrix_1)
matrix_3 = torch.tensor(matrix_1)

# log
print(f"matrix_1:\n{matrix_1}\nndim : 2\ndtype: {type(matrix_1[0][0])}")
print('-' * 50)
print(f"matrix_2:\n{matrix_2}\nmatrix_2.ndim : {matrix_2.ndim}\nmatrix_2.shape: {matrix_2.shape}\nmatrix_2.dtype: numpy.{matrix_2.dtype}")
print('-' * 50)
print(f"matrix_3:\n{matrix_3}\nmatrix_3.ndim : {matrix_3.ndim}\nmatrix_3.shape: {matrix_3.shape}\nmatrix_3.dtype: {matrix_3.dtype}")

matrix_1:
[[0, 1], [2, 3]]
ndim : 2
dtype: <class 'int'>
--------------------------------------------------
matrix_2:
[[0 1]
 [2 3]]
matrix_2.ndim : 2
matrix_2.shape: (2, 2)
matrix_2.dtype: numpy.int32
--------------------------------------------------
matrix_3:
tensor([[0, 1],
        [2, 3]])
matrix_3.ndim : 2
matrix_3.shape: torch.Size([2, 2])
matrix_3.dtype: torch.int64


In [34]:
# 3-dimensional list/array/tensor
list_3d_1 = [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array_3d_1 = np.array(list_3d_1)
tensor_3d_1 = torch.tensor(list_3d_1)

# log
print(f"lst:\n{list_3d_1}\nndim : 3\ndtype: {type(list_3d_1[0][0][0])}")
print('-' * 50)
print(f"arr:\n{array_3d_1}\narr.ndim : {array_3d_1.ndim}\narr.shape: {array_3d_1.shape}\narr.dtype: numpy.{array_3d_1.dtype}")
print('-' * 50)
print(f"tsr:\n{tensor_3d_1}\ntsr.ndim : {tensor_3d_1.ndim}\ntsr.shape: {tensor_3d_1.shape}\ntsr.dtype: {tensor_3d_1.dtype}")

lst:
[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
ndim : 3
dtype: <class 'int'>
--------------------------------------------------
arr:
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
arr.ndim : 3
arr.shape: (2, 2, 2)
arr.dtype: numpy.int32
--------------------------------------------------
tsr:
tensor([[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]])
tsr.ndim : 3
tsr.shape: torch.Size([2, 2, 2])
tsr.dtype: torch.int64


# PyTorch Tensors

## Ones, Zeros, Full, Empty
📝 **Docs**:
   - Creation Ops: [pytorch.org/docs/stable/torch.html#creation-ops](https://pytorch.org/docs/stable/torch.html#creation-ops)

In [35]:
# ones
ones_1 = torch.ones(size=())
ones_2 = torch.ones(size=(2, 2))

# zeros
zeros_1 = torch.zeros(size=(2,))
zeros_2 = torch.zeros(size=(3,), dtype=torch.int16)

# full
full_1 = torch.full(size=(3,), fill_value=3, dtype=torch.int16)

# empty
empty_1 = torch.empty(size=(2, 3))

# log
for variable in ['ones_1', 'ones_2', 'zeros_1', 'zeros_2', 'full_1', 'empty_1']:
    print(f"{variable}:\n{eval(variable)}")
    print(f"{variable}.size() : {eval(variable).size()}")
    print(f"{variable}.ndim   : {eval(variable).ndim}")
    print(f"{variable}.dtype  : {eval(variable).dtype}")
    print(f"type({variable})  : {type(eval(variable))}")
    print('-' * 50)

ones_1:
1.0
ones_1.size() : torch.Size([])
ones_1.ndim   : 0
ones_1.dtype  : torch.float32
type(ones_1)  : <class 'torch.Tensor'>
--------------------------------------------------
ones_2:
tensor([[1., 1.],
        [1., 1.]])
ones_2.size() : torch.Size([2, 2])
ones_2.ndim   : 2
ones_2.dtype  : torch.float32
type(ones_2)  : <class 'torch.Tensor'>
--------------------------------------------------
zeros_1:
tensor([0., 0.])
zeros_1.size() : torch.Size([2])
zeros_1.ndim   : 1
zeros_1.dtype  : torch.float32
type(zeros_1)  : <class 'torch.Tensor'>
--------------------------------------------------
zeros_2:
tensor([0, 0, 0], dtype=torch.int16)
zeros_2.size() : torch.Size([3])
zeros_2.ndim   : 1
zeros_2.dtype  : torch.int16
type(zeros_2)  : <class 'torch.Tensor'>
--------------------------------------------------
full_1:
tensor([3, 3, 3], dtype=torch.int16)
full_1.size() : torch.Size([3])
full_1.ndim   : 1
full_1.dtype  : torch.int16
type(full_1)  : <class 'torch.Tensor'>
---------------------

## Index & Slice
   - Indexing a tensor in the PyTorch C++ API works very similar to the Python API.
   - All index types such as `None` / `...` / `integer` / `boolean` / `slice` / `tensor` are available in the C++ API, making translation from Python indexing code to C++ very simple.
   
📝 **Docs**:
   - Tensor Indexing API: [pytorch.org/cppdocs/notes/tensor_indexing.html](https://pytorch.org/cppdocs/notes/tensor_indexing.html)

In [36]:
tensor_2d_1 = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# index
index_1 = tensor_2d_1[0]
index_2 = tensor_2d_1[1]
index_3 = tensor_2d_1[-1]
index_4 = tensor_2d_1[0, 0]
index_5 = tensor_2d_1[2, -2]

# log
print(f"index_1: {index_1}")
print(f"index_2: {index_2}")
print(f"index_3: {index_3}")
print(f"index_4: {index_4}")
print(f"index_5: {index_5}")

index_1: tensor([1, 2, 3, 4])
index_2: tensor([5, 6, 7, 8])
index_3: tensor([ 9, 10, 11, 12])
index_4: 1
index_5: 11


In [37]:
tensor_2d_2 = torch.arange(12).reshape((3, 4))

# slice
slice_1 = tensor_2d_2[0, :]    # same as tensor_2d_2[0]
slice_2 = tensor_2d_2[:, 1]
slice_3 = tensor_2d_2[:2, 2:]
slice_4 = tensor_2d_2[-1:, 0]

# log
print(f"slice_1:\n{slice_1}\n")
print(f"slice_2:\n{slice_2}\n")
print(f"slice_3:\n{slice_3}\n")
print(f"slice_4:\n{slice_4}")

slice_1:
tensor([0, 1, 2, 3])

slice_2:
tensor([1, 5, 9])

slice_3:
tensor([[2, 3],
        [6, 7]])

slice_4:
tensor([8])


## Math operations

📝 **Docs**:
   - Math operations: [pytorch.org/docs/stable/torch.html#math-operations](https://pytorch.org/docs/stable/torch.html#math-operations)

### Pointwise Ops

In [38]:
tensor_2d_3 = torch.arange(4).reshape(2, 2)
tensor_2d_4 = torch.full(size=(2, 2), fill_value=2, dtype=torch.int64)

# arithmetic operations
arithmetic_1 = tensor_2d_3 + tensor_2d_4   # torch.add
arithmetic_2 = tensor_2d_3 - tensor_2d_4   # torch.sub
arithmetic_3 = tensor_2d_3 * tensor_2d_4   # torch.multiply
arithmetic_4 = tensor_2d_3 / tensor_2d_4   # torch.divide
arithmetic_5 = tensor_2d_3 // tensor_2d_4  # torch.floor_divide
arithmetic_6 = tensor_2d_3 % tensor_2d_4   # torch.remainder
arithmetic_7 = tensor_2d_3 ** tensor_2d_4  # torch.power

# log
print(f"tensor_2d_3:\n{tensor_2d_3}\n")
print(f"tensor_2d_4:\n{tensor_2d_4}")
print('-' * 50)
for i in range(7):
    print(f"arithmetic_{i+1}:\n{eval(f'arithmetic_{i+1}')}\n")

tensor_2d_3:
tensor([[0, 1],
        [2, 3]])

tensor_2d_4:
tensor([[2, 2],
        [2, 2]])
--------------------------------------------------
arithmetic_1:
tensor([[2, 3],
        [4, 5]])

arithmetic_2:
tensor([[-2, -1],
        [ 0,  1]])

arithmetic_3:
tensor([[0, 2],
        [4, 6]])

arithmetic_4:
tensor([[0.0000, 0.5000],
        [1.0000, 1.5000]])

arithmetic_5:
tensor([[0, 0],
        [1, 1]])

arithmetic_6:
tensor([[0, 1],
        [0, 1]])

arithmetic_7:
tensor([[0, 1],
        [4, 9]])



#### Broadcasting
   - [pytorch.org/docs/stable/notes/broadcasting.html](https://pytorch.org/docs/stable/notes/broadcasting.html)

In [39]:
tensor_2d_5 = torch.arange(4).reshape(2, 2) + 1
tensor_2d_6 = torch.tensor([[1], [2]])

# broadcasting
broadcasting_1 = tensor_2d_5 + 1
broadcasting_2 = tensor_2d_5 + tensor_2d_6

# log
print(f"tensor_2d_5:\n{tensor_2d_5}\n")
print(f"tensor_2d_5:\n{tensor_2d_6}")
print('-' * 50)
print(f"broadcasting_1:\n{broadcasting_1}\n")
print(f"broadcasting_2:\n{broadcasting_2}\n")

tensor_2d_5:
tensor([[1, 2],
        [3, 4]])

tensor_2d_5:
tensor([[1],
        [2]])
--------------------------------------------------
broadcasting_1:
tensor([[2, 3],
        [4, 5]])

broadcasting_2:
tensor([[2, 3],
        [5, 6]])



## Reshape & View
   - torch.Tensor.**view**:
      - requires the tensor to be contiguous
      - less flexible due to the contiguity requirement
      - generally faster since it doesn't involve copying data, just changes the metadata
      - [pytorch.org/docs/stable/generated/torch.Tensor.reshape.html](https://pytorch.org/docs/stable/generated/torch.Tensor.reshape.html)
   - torch.Tensor.**reshape**:
      - it can handle non-contiguous tensors by copying data if necessary
      - more flexible as it can work with both contiguous and non-contiguous tensors
      - might be slower if it needs to copy the data to create a contiguous block
      - [pytorch.org/docs/stable/generated/torch.Tensor.view.html](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html)

**Note**:
   - it is advisable to use `reshape`, which returns a `view` if the shapes are compatible, and copies otherwise.


In [40]:
tensor_2d_7 = torch.arange(16).reshape(4, 4)

# reshape
reshape_1 = tensor_2d_7.reshape(2, 8)
reshape_2 = tensor_2d_7.reshape(2, -1, 2)

# log
print(f"tensor_2d_7:\n{tensor_2d_7}\n")
print('-' * 50)
print(f"reshape_1:\n{reshape_1}")
print(f"reshape_1.shape: {reshape_1.shape}\n")
print(f"reshape_2:\n{reshape_2}")
print(f"reshape_2.shape: {reshape_2.shape}")

tensor_2d_7:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

--------------------------------------------------
reshape_1:
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]])
reshape_1.shape: torch.Size([2, 8])

reshape_2:
tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]])
reshape_2.shape: torch.Size([2, 4, 2])


In [41]:
# assignment by index
tensor_2d_7[0, 0] = 100

# log
print(f"tensor_2d_7:\n{tensor_2d_7}\n")
print(f"reshape_1:\n{reshape_1}\n")

tensor_2d_7:
tensor([[100,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [ 12,  13,  14,  15]])

reshape_1:
tensor([[100,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15]])



## Mutable Objects
   - mutable objects refer to objects that can be modified after they are created.
   - For example, `list`, `numpy.ndarray`, `torch.Tensor` are mutable objects.

### Copy Tensors
   - `torch.clone`: 
      - creates a hard/deep copy
      - This function is differentiable, so gradients will flow back from the result of this operation to `input`
   - [pytorch.org/docs/stable/generated/torch.clone.html](https://pytorch.org/docs/stable/generated/torch.clone.html)

In [42]:
tensor_1d_1 = torch.zeros(size=(5,))

# clone
clone_1 = tensor_1d_1.clone()

# assignment by index
tensor_1d_1[0] = 1

# log
print(f"clone_1: {clone_1}")

clone_1: tensor([0., 0., 0., 0., 0.])


### torch.Tensor to numpy.ndarray
   - [pytorch.org/docs/stable/generated/torch.Tensor.numpy.html](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html)

In [43]:
tensor_1d_2 = torch.tensor([1, 2, 6, 3])

# convert + shared memory
tensor_to_numpy_1 = tensor_1d_2.numpy()

# convert + copy
tensor_to_numpy_2 = np.array(tensor_1d_2)

# assignment by index
tensor_1d_2[0] = 0

# log
print(f"tensor_1d_2        : {tensor_1d_2}")
print(f"type(tensor_1d_2)  : {type(tensor_1d_2)}")
print('-' * 50)
print(f"tensor_to_numpy_1        : {tensor_to_numpy_1}")
print(f"type(tensor_to_numpy_1)  : {type(tensor_to_numpy_1)}\n")
print(f"tensor_to_numpy_2        : {tensor_to_numpy_2}")
print(f"type(tensor_to_numpy_2)  : {type(tensor_to_numpy_2)}")

tensor_1d_2        : tensor([0, 2, 6, 3])
type(tensor_1d_2)  : <class 'torch.Tensor'>
--------------------------------------------------
tensor_to_numpy_1        : [0 2 6 3]
type(tensor_to_numpy_1)  : <class 'numpy.ndarray'>

tensor_to_numpy_2        : [1 2 6 3]
type(tensor_to_numpy_2)  : <class 'numpy.ndarray'>


### numpy.ndarray to torch.Tensor
   - [pytorch.org/docs/stable/generated/torch.from_numpy.html](https://pytorch.org/docs/stable/generated/torch.from_numpy.html)

In [44]:
array_1d_1 = np.array([1, 4, 2, 3])

# convert + shared memory
numpy_to_tensor_1 = torch.from_numpy(array_1d_1)

# convert + copy
numpy_to_tensor_2 = torch.tensor(array_1d_1)

# assignment by index
array_1d_1[0] = 0

# log
print(f"array_1d_1       : {array_1d_1}")
print(f"type(array_1d_1) : {type(array_1d_1)}")
print('-' * 50)
print(f"numpy_to_tensor_1       : {numpy_to_tensor_1}")
print(f"type(numpy_to_tensor_1) : {type(numpy_to_tensor_1)}\n")
print(f"numpy_to_tensor_2       : {numpy_to_tensor_2}")
print(f"type(numpy_to_tensor_2) : {type(numpy_to_tensor_2)}")

array_1d_1       : [0 4 2 3]
type(array_1d_1) : <class 'numpy.ndarray'>
--------------------------------------------------
numpy_to_tensor_1       : tensor([0, 4, 2, 3], dtype=torch.int32)
type(numpy_to_tensor_1) : <class 'torch.Tensor'>

numpy_to_tensor_2       : tensor([1, 4, 2, 3], dtype=torch.int32)
type(numpy_to_tensor_2) : <class 'torch.Tensor'>


### In-Place Operations
   - Operations that have a `_` suffix are in-place.
   - In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history.
   - Hence, their use is discouraged.

📚 **Tutorials**:
   - in-place operations: [pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#:~:text=3.%2C%203.%2C%203.%5D%5D\)-,In%2Dplace%20operations,-Operations%20that%20have)

In [45]:
tensor_1d_3 = torch.tensor([1.0, 2.0, 3.0, 4.0])

# in-place addition
tensor_1d_3.add_(2)  # tensor_1d_3 += 2

# out-of-place addition
another_tensor = torch.add(tensor_1d_3, 2)  # another_tensor = tensor_1d_3 + 2

# log
print(f"tensor_1d_3    : {tensor_1d_3}")
print(f"another_tensor : {another_tensor}")

tensor_1d_3    : tensor([3., 4., 5., 6.])
another_tensor : tensor([5., 6., 7., 8.])


## GPU Acceleration
   - PyTorch relies on the underlying [CUDA](https://developer.nvidia.com/cuda-gpus) [NVIDIA GPUs] and [ROCm](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/3rd-party-support-matrix.html#deep-learning) [AMD GPUs] libraries for GPU support
   - [pytorch.org/docs/stable/notes/cuda.html](https://pytorch.org/docs/stable/notes/cuda.html)

✍️ **Notes**:
   - Tensors on the `GPU` cannot be directly converted to `np.ndarray` or other structures that do not support GPU operations.
   - You can use `torch.backends.rocm.is_available()` instead of `torch.cuda.is_available()` for clarity if targeting AMD GPUs.
   - The version of PyTorch you're using must include the ROCm-specific attribute to run `torch.backends.rocm.is_available()`.

In [46]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

# alternative
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')

# log
print(f"device: {device}")

device: cuda


In [47]:
if torch.cuda.is_available():

    # number of cuda devices
    num_cuda_devices = torch.cuda.device_count()
    print(f"num_cuda_devices  : {num_cuda_devices}")

    # cuda models
    for i in range(num_cuda_devices):
        print(f"cuda {i}:")
        print(f"\tname                  : {torch.cuda.get_device_properties(i).name}")
        print(f"\ttotal_memory          : {torch.cuda.get_device_properties(i).total_memory} bytes")
        print(f"\tmulti_processor_count : {torch.cuda.get_device_properties(i).multi_processor_count}")

num_cuda_devices  : 1
cuda 0:
	name                  : NVIDIA GeForce GTX 1650
	total_memory          : 4294639616 bytes
	multi_processor_count : 14


In [48]:
tensor_1d_4 = torch.ones(5)                 # CPU                          [default]
tensor_1d_5 = torch.ones(5, device=device)  # CPU/GPU (depends on device)  [dynamic]
tensor_1d_6 = tensor_1d_3.to(device)        # CPU/GPU (depends on device)  [dynamic]
tensor_1d_7 = tensor_1d_3.cuda()            # GPU                          [static]

# log
print(f"tensor_1d_4        : {tensor_1d_4}")
print(f"tensor_1d_4.device : {tensor_1d_4.device}\n")
print(f"tensor_1d_5        : {tensor_1d_5}")
print(f"tensor_1d_5.device : {tensor_1d_5.device}\n")
print(f"tensor_1d_6        : {tensor_1d_6}")
print(f"tensor_1d_6.device : {tensor_1d_6.device}\n")
print(f"tensor_1d_7        : {tensor_1d_7}")
print(f"tensor_1d_7.device : {tensor_1d_7.device}")

tensor_1d_4        : tensor([1., 1., 1., 1., 1.])
tensor_1d_4.device : cpu

tensor_1d_5        : tensor([1., 1., 1., 1., 1.], device='cuda:0')
tensor_1d_5.device : cuda:0

tensor_1d_6        : tensor([3., 4., 5., 6.], device='cuda:0')
tensor_1d_6.device : cuda:0

tensor_1d_7        : tensor([3., 4., 5., 6.], device='cuda:0')
tensor_1d_7.device : cuda:0


In [49]:
tensor_1d_8 = torch.ones(size=(5,), device=device)

# torch.Tensor to numpy.ndarray
try:
    tensor_1d_8.numpy()
except TypeError as e:
    print(e)

can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.


In [50]:
tensor_1d_9 = torch.ones(size=(5,), device=device)

# torch.Tensor to numpy.ndarray
tensor_to_numpy_3 = tensor_1d_9.cpu().numpy()

# log
print(f"tensor_to_numpy_3       : {tensor_to_numpy_3}")
print(f"type(tensor_to_numpy_3) : {type(tensor_to_numpy_3)}")

tensor_to_numpy_3       : [1. 1. 1. 1. 1.]
type(tensor_to_numpy_3) : <class 'numpy.ndarray'>


## Reproducibility
   - **Seed**: An initial value used to initialize a pseudo-random number generator, ensuring reproducibility of random sequences.

   - **Platform and Release Variations**:
      - Completely reproducible results are not guaranteed across:
         - Different PyTorch releases
         - Individual commits
         - Different platforms (e.g., CPU vs. GPU, different OS)

   - **Performance Trade-offs**:
      - Deterministic operations are often slower than nondeterministic operations.
  
   - **Benefits of Determinism**:
      - Determinism can save time in development by facilitating:
         - Experimentation
         - Debugging
         - Testing

📝 **Docs**:
   - Reproducibility: [pytorch.org/docs/stable/notes/randomness.html](https://pytorch.org/docs/stable/notes/randomness.html)

In [51]:
# set a seed for both CPU & GPU
torch.manual_seed(42)

# log
print(f"torch.get_rng_state()[0]      : {torch.get_rng_state()[0]}")
print(f"torch.cuda.get_rng_state()[0] : {torch.cuda.get_rng_state()[0]}")

torch.get_rng_state()[0]      : 42
torch.cuda.get_rng_state()[0] : 42


In [59]:
# set a seed only for GPU
torch.cuda.manual_seed(0)

# log
print(f"torch.get_rng_state()[0]      : {torch.get_rng_state()[0]}")
print(f"torch.cuda.get_rng_state()[0] : {torch.cuda.get_rng_state()[0]}")

torch.get_rng_state()[0]      : 42
torch.cuda.get_rng_state()[0] : 0


### `torch.backends.cudnn.deterministic`
   - This flag ensures that the CUDA Deep Neural Network library (cuDNN) uses deterministic algorithms.
   - the results will be the same for every run when the same input and seed are provided.
   - Default value is `False`.

💥 **Impact**
   - When set to `True`, It can slow down your computations because deterministic algorithms are typically slower due to fewer optimizations

📝 **Docs**:
   - [pytorch.org/docs/stable/backends.html#torch.backends.cudnn.deterministic](https://pytorch.org/docs/stable/backends.html#torch.backends.cudnn.deterministic)

In [ ]:
torch.backends.cudnn.deterministic = True

### `torch.backends.cudnn.benchmark`
   - This flag enables the cuDNN auto-tuner to find the best algorithm for your hardware.
   - It is useful when the input sizes to your model are changing or not fixed.
   - Default value is `False`

💥 **Impact**
   - When set to `True`, cuDNN will select the best algorithm for your hardware, potentially improving performance.
   - If you need exact reproducibility, you should not set benchmark to `True`!

📝 **Docs**:
   - [pytorch.org/docs/stable/backends.html#torch.backends.cudnn.benchmark](https://pytorch.org/docs/stable/backends.html#torch.backends.cudnn.benchmark)

In [ ]:
torch.backends.cudnn.benchmark = False

### `torch.use_deterministic_algorithms`
   - This function ensures that all the operations that could be non-deterministic are forced to use deterministic algorithms.
   - Default value is `False`.

💥 **Impact**
   - When set to `True`, This could lead to slower performance as deterministic algorithms are often slower due to the lack of certain optimizations.

📝 **Docs**:
   - [pytorch.org/docs/stable/generated/torch.use_deterministic_algorithms.html#torch.use_deterministic_algorithms](https://pytorch.org/docs/stable/generated/torch.use_deterministic_algorithms.html#torch.use_deterministic_algorithms)

In [ ]:
torch.use_deterministic_algorithms(True)

# check
print(f"torch.are_deterministic_algorithms_enabled(): {torch.are_deterministic_algorithms_enabled()}")

torch.are_deterministic_algorithms_enabled(): True


## Random Sampling from a Distribution
   - Random sampling from a distribution refers to the process of generating random samples from a specific probability distribution.
   - In most cases, the goal is to sample from these distributions to simulate or model real-world phenomena.

📝 **Docs**:
   - [pytorch.org/docs/stable/torch.html#random-sampling](https://pytorch.org/docs/stable/torch.html#random-sampling)

In [56]:
# a tensor filled with random numbers from a uniform distribution on the interval [0,1)
rand_1 = torch.rand(size=(5,))

# log
print(f"rand_1       : {rand_1}")
print(f"rand_1.dtype : {rand_1.dtype}")

rand_1       : tensor([0.8823, 0.9150, 0.3829, 0.9593, 0.3904])
rand_1.dtype : torch.float32


In [57]:
# a tensor of random numbers drawn from separate normal distributions
normal_1 = torch.normal(mean=0, std=.1, size=(5,))

# log
print(f"normal_1        : {normal_1}")
print(f"normal_1.mean() : {normal_1.mean()}")
print(f"normal_1.std()  : {normal_1.std()}")
print(f"normal_1.dtype  : {normal_1.dtype}")

normal_1        : tensor([ 0.0326, -0.0868,  0.1523,  0.0665, -0.1032])
normal_1.mean() : 0.01226949505507946
normal_1.std()  : 0.10736953467130661
normal_1.dtype  : torch.float32


## `torch.Tensor.item()`
   - What you see is not necessarily the actual value!
   - [pytorch.org/docs/stable/generated/torch.Tensor.item.html](https://pytorch.org/docs/stable/generated/torch.Tensor.item.html)

In [58]:
tensor_1d_10 = torch.rand(size=(6,))

# item()
value_1 = tensor_1d_10[0]
value_2 = tensor_1d_10[0].item()

# log
print(f"tensor_1d_10: {tensor_1d_10}")
print('-' * 50)
print(f"value_1       : {value_1}")
print(f"value_1.dtype : {value_1.dtype}\n")
print(f"value_2       : {value_2}")
print(f"type(value_2) : {type(value_2)}")

tensor_1d_10: tensor([0.5739, 0.2666, 0.6274, 0.2696, 0.4414, 0.2969])
--------------------------------------------------
value_1       : 0.5739044547080994
value_1.dtype : torch.float32

value_2       : 0.5739044547080994
type(value_2) : <class 'float'>


## Miscellaneous

### `torch.float32` is preferred over `torch.float64` in most deep learning tasks
   1. **Performance and Speed**:
      - Single-precision (`torch.float32`) operations are faster and require less computational effort compared to double-precision (`torch.float64`).
   1. **Memory Usage**:
      - `torch.float32` uses 32 bits (4 bytes) per value, while `torch.float64` uses 64 bits (8 bytes), leading to lower memory requirements for `float32`.
   1. **Adequate Precision**:
      - For most deep learning tasks, `torch.float32` offers sufficient precision. Double-precision (`torch.float64`) is often unnecessary.
   1. **Energy Efficiency**:
      - Single-precision arithmetic is more energy-efficient than double-precision, making it ideal for tasks that demand lower power consumption.
   1. **Industry Standards**:
      - `torch.float32` is the standard in deep learning frameworks and is widely used across research and production environments.
   1. **Hardware Constraints**:
      - Many hardware platforms, including embedded systems and mobile devices, have limited computational resources and memory, making `torch.float32` more suitable.

✍️ **Notes**:
- `torch.float32` is also called `float` or `single-precision`.
- `torch.float64` is also called `double` or `double-precision`.